---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: camunda-docs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: ${HOME}/camunda-docs
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: camunda-docs-pvc
  namespace: camunda
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: camunda-docs-pv
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: camunda-connectors-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: ${HOME}/camunda-connectors
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: camunda-connectors-custom
  namespace: camunda
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: camunda-connectors-pv
  resources:
    requests:
      storage: 500Mi
